---
- name: configure test server
  hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy Capstone-Insurance-Project
    command: sudo docker run -itd -p 8085:8081 loksmohan2000/insure-me-app:1.0 
